### ISSUE TITLE
Error while Loading Plugins in Riemann Config

### ISSUE THREAD

**Issue by MohamedHz** [avishai-ish-shalom/riemann-rabbitmq-plugin#3]
Hi,

I am a newbie to this project and trying to  load the plugins but unfortunately facing an error as below:
# Error

INFO [2016-06-16 16:34:39,662] main - riemann.bin - Loading /etc/riemann/riemann.config
INFO [2016-06-16 16:34:39,748] main - riemann.plugin - walking classpath to find plugins
INFO [2016-06-16 16:34:39,957] main - riemann.plugin - loading plugin: rabbitmq-plugin
Exception in thread "main" java.io.FileNotFoundException: Could not locate langohr/core__init.class or langohr/core.clj on classpath., compiling:(riemann_rabbitmq_plugin/core.clj:1:1)

Thank you in advance.

**Comment by nukemberg** [comment]
did you use the uberjar?

**Comment by MohamedHz** [comment]
@avishai-ish-shalom Thanks for your valuable reply. 
Yes I have compiled with uberjar and added the jar file in /etc/sysconfig/riemann ( EXTRA_CLASSPATH=/usr/lib/riemann/riemann-rabbitmq-plugin-0.1.1-SNAPSHOT.jar ).

_**I am newbie to this project and not sure whether I am using correct syntax in riemann.config file .  I need to push the riemann events to rabbitmq server and the config file is mentioned below:**_

# 

; -_\- mode: clojure; -_-
; vim: filetype=clojure

(logging/init {:file "/var/log/riemann/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"](tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 5)

(load-plugins)

(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    (default :ttl 60
      index

(rabbitmq-plugin/rabbitmq-consumer {
                       :parser-fn rabbitmq-plugin/logstash-parser ; message parsing function, the sample function here is the default
                       :prefetch-count 100 ; this is the default
                       :bindings [{
                         :opts {:durable false :auto-delete true} ; this is the default
                         :queue "" ; the default is "" which means auto-generated queue name
                         :bind-to {"exchange", ["binding-key"]} ; also works with single non-seq binding key
                         :tags ["amqp"] ; will be added to event tags
                       }]
                       :connection-opts {:host "192.168.2.31" :port 5672 :username "mqadmin" :passowrd "mqadmin"} ; default is {}
                       })
)))

I hope you will help me to connect the rabbitmq server .Thank you in advance.

**Comment by nukemberg** [comment]
When you build the project you will have two jar file, you need the one called _standalone_ - it's also much bigger than the other one. make sure it is in the riemann classpath, e.g. by changing `EXTRA_CLASSPATH` in `/etc/default/riemann`. Please go over the readme.
